### ISSUE TITLE
强烈关注，能否发布个在线阅读的gitbook.io地址啊

### ISSUE THREAD

**Issue by luodaoyi** [sg552/happy_book_rails#1]

**Comment by luodaoyi** [comment]
好吧 我暂时弄了一个 如果作者不愿意 或者觉得不妥 我删掉就行 [https://luodaoyi.gitbooks.io/happy_book_rails](https://luodaoyi.gitbooks.io/happy_book_rails)

**Comment by sg552** [comment]
我弄了呀.  回头我把地址放在这里.

**Comment by sg552** [comment]
https://sg552.gitbooks.io/happy_book_rails/content/

**Comment by luodaoyi** [comment]
好的 那我就删掉这个了
